// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA3DgFtc8u98ArQsoj2_sq1xEqPpSoSic',
    appId: '1:920319328076:web:31d56392b94496124559e9',
    messagingSenderId: '920319328076',
    projectId: 'fir-crud-basics-37bb8',
    authDomain: 'fir-crud-basics-37bb8.firebaseapp.com',
    storageBucket: 'fir-crud-basics-37bb8.firebasestorage.app',
    measurementId: 'G-2Z3HBWER1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkRFzCTt0Kip13C6ss-OhQ53jR4kGlGm8',
    appId: '1:920319328076:android:0b4adee3215a6a3e4559e9',
    messagingSenderId: '920319328076',
    projectId: 'fir-crud-basics-37bb8',
    storageBucket: 'fir-crud-basics-37bb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSl8GIyZcFzWikqPFBH70iUG5DbtUtHTs',
    appId: '1:920319328076:ios:943a6b998fef8d944559e9',
    messagingSenderId: '920319328076',
    projectId: 'fir-crud-basics-37bb8',
    storageBucket: 'fir-crud-basics-37bb8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSl8GIyZcFzWikqPFBH70iUG5DbtUtHTs',
    appId: '1:920319328076:ios:943a6b998fef8d944559e9',
    messagingSenderId: '920319328076',
    projectId: 'fir-crud-basics-37bb8',
    storageBucket: 'fir-crud-basics-37bb8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA3DgFtc8u98ArQsoj2_sq1xEqPpSoSic',
    appId: '1:920319328076:web:9baa584ae72a12d54559e9',
    messagingSenderId: '920319328076',
    projectId: 'fir-crud-basics-37bb8',
    authDomain: 'fir-crud-basics-37bb8.firebaseapp.com',
    storageBucket: 'fir-crud-basics-37bb8.firebasestorage.app',
    measurementId: 'G-BWFW8XMMCD',
  );
}
